export const THEMES = [
    "light",
    "dark",
    "cupcake",
    "bumblebee",
    "emerald",
    "corporate",
    "synthwave",
    "retro",
    "cyberpunk",
    "valentine",
    "halloween",
    "garden",
    "forest",
    "aqua",
    "lofi",
    "pastel",
    "fantasy",
    "wireframe",
    "black",
    "luxury",
    "dracula",
    "cmyk",
    "autumn",
    "business",
    "acid",
    "lemonade",
    "night",
    "coffee",
    "winter",
    "dim",
    "nord",
    "sunset",
    "zineb",
    "adam"
];

export const PREVIEW_MESSAGES = [
    { id: 1, content: "Helloooo Adaaaaaaaaaaam", isSent: false },
    { id: 2, content: "Helloooo Ziiiiineeeeeeeeeeb", isSent: true },
]  